### ISSUE TITLE
get T and M by column names

### ISSUE THREAD

**Issue by wkc1986** [LukasBurger/MethylSeekR#1]
In `trainPMDHMM.R` lines 10-11:

```r
 T <- as.numeric(values(m[indx])[, 1])
  M <- as.numeric(values(m[indx])[, 2])
```

So T and M must be columns 1 and 2 of the input. On the other hand, the documentation just says the data structure needs columns T and M, with no hint that the column ordering matters. Perhaps one or the other should be changed?

**Comment by LukasBurger** [comment]
Hi, sorry for the late reply, I was away. Thanks for pointing this out, I will fix it in the vignette.
