### ISSUE TITLE
No PMDs on all samples. alphaDist consistently unimodal below 1.

### ISSUE THREAD

**Issue by Blosberg** [LukasBurger/MethylSeekR#2]
Thanks for providing this great package.
I started using it this week and I am having the problem of _always_ being led to the conclusion of no PMDs present, even when I strongly suspect that some should be found.

Specifically, I'm following the instructions from [this vignette](http://www.bioconductor.org/packages/release/bioc/vignettes/MethylSeekR/inst/doc/MethylSeekR.pdf), where it states:

> Generally, there is evidence for PMDs if the distribution of α-values is bimodal or long-tailed with a significant fraction of α values larger or equal 1.

I can see the same bimodal feature shown in the example from the vignette _when using that data,_ but never with anything else. All of my samples show a clearly unimodal alpha-distribution with nothing significantly above 1, so I concluded, initially, that there were no PMDs in my samples. As a control, however, I then ran the same process on several samples where I'd expect to see PMDs, and still saw a uni-modal alpha distribution. 

For example: from additional file 1 from [Salhab et al](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-018-1510-5#Sec19) I used [one of the macrophage samples]( http://ftp.ebi.ac.uk/pub/databases/blueprint/data/homo_sapiens/GRCh38/cord_blood/S00BHQ/macrophage/Bisulfite-Seq/CNAG/S00BHQ51.CPG_methylation_calls.sdgdll.GRCh38.20160531.bw) and converted it to the appropriate tab format and read it into a GRanges object `meth.gr` (after filtering for minimum coverage of 10 --I tried again with no coverage filter and the conclusion didn't change.):

```
 > meth.gr
GRanges object with 20143942 ranges and 2 metadata columns:
             seqnames    ranges strand |         T         M
                <Rle> <IRanges>  <Rle> | <numeric> <numeric>
         [1]     chr1     10648      * |        12        11
         [2]     chr1     10658      * |        12         8
         [3]     chr1     10660      * |        11         5
         [4]     chr1     10663      * |        11         8
         [5]     chr1     10665      * |        13         9
```

with columns for [chromosome, position (base1) of CG,  Total counts,  Methylated counts]. I then ran the following:

```
PMDsegments.gr <- segmentPMDs( m=meth.gr,
                               chr.sel    = "chr1",
                               seqLengths = sLengths,
                               num.cores  = 1,
                               pdfFilename =  "alphaDist_example.pdf")  )
```

(I also ran simple `plotAlphaDistributionOneChr()` )
and the resulting alphaDist looks clearly unimodal, well below 1, as does every other sample I apply this procedure to. I do get a set of PMDs output, but I'm not sure if I should trust these, as the documentation makes it clear that the presence of valid PMDs depends on bimodal alpha. 
Am I doing something wrong, or is this constraint of bimodal alpha more flexible than the vignette indicated? if so, can I ignore this alpha distribution and still use the pmds I'm obtaining? if not, can you suggest another sample where I can see this bimodal curve and definitively find PMDs?

**Edit:** _additional info:_

```
> packageVersion("MethylSeekR")
[1] ‘1.26.0’
> R.Version()$version.string
[1] "R version 3.6.3 (2020-02-29)"
```

Thanks in advance for any insight you can offer.

**Comment by LukasBurger** [comment]
Hi, thanks for showing interest in our package. MethylSeekR was developed at a time when PMDs were characterized by a roughly uniform distribution of methylation levels and therefore alpha was chosen to measure to what extent the distribution of methylation levels in a sliding window is uniform (PMD) versus polarized (non-PMD). Is it possible that in your samples the PMDs actually have very low methylation levels (not uniform ones) and thus the alpha value is not the right measure? The IMR90 methylome in https://www.nature.com/articles/nature08514 would be a good example of a methylome with PMDs.
