### ISSUE TITLE
How to get the SNVs  for our own methylated data

### ISSUE THREAD

**Issue by Xiangyi-Deng** [LukasBurger/MethylSeekR#4]
Hello there,

It is a great package and I am trying to do some data analysis.

I practiced your tutorial code  and I have a small question  about the function` read SNVs data` and `removeSNPs`.

I want to know if the SNVs files should be achieved from somewhere ? Or shall I  do it by myself through your package ?

I think filter SNVs is a necessary step in the whole workflow in your article.

Thank you.

Best,
xiangyi

**Comment by Xiangyi-Deng** [comment]
Hi @LukasBurger 

I think I may find the SNVs file for hg38 from [here].(https://melbourne.figshare.com/articles/dataset/Common_SNVS_hg38/17032163) 

You can have a look. I believe it is suitable for all the chromosomes not only for only one.

I hope you can tell me if it is right or give me some advice on this question.

Sincerely,
xiangyi

**Comment by LukasBurger** [comment]
Hi Xiangyi
Thanks for showing interest in MethylSeekR. MethylSeekR assumes that you already know the SNPs of your cell type/line. In case you don’t, you can try to call them directly from your bisulfite data (see eg here https://genomebiology.biomedcentral.com/articles/10.1186/gb-2012-13-7-r61) or you can use common SNPs from a database as for example dbSNP (https://www.ncbi.nlm.nih.gov/snp/)
Hope that helps,
best
Lukas

On 11 Apr 2023, at 13:31, DengEr-1993 ***@***.***> wrote:



Hello there,

It is a great package and I am trying to do some data analysis.

I practiced your tutorial code and I have a small question about the function read SNVs data and removeSNPs.

I want to know if the SNVs files should be achieved from somewhere ? Or shall I do it by myself through your package ?

I think filter SNVs is a necessary step in the whole workflow in your article.

Thank you.

Best,
xiangyi
