### ISSUE TITLE
If MethylseekR can  do PMD analysis on the whole genome not only focus on one chromosome ?

### ISSUE THREAD

**Issue by Xiangyi-Deng** [LukasBurger/MethylSeekR#5]
hello @LukasBurger , I have a small question that need your help.

I can do PMD analysis according to your tutorial of MethylseekR mainly focus on  one specific chromosome.

But if it is possible to do similar or the same analysis based on all the chromosomes ? Not only one chromosome.

Because I want to look four type of segments  (HMD,PMD,LMR,UMR) in one sample data. 

Could you give some advice on this question. 

Thanks in advance.

Best,
xiangyi

**Comment by LukasBurger** [comment]
Hi Xiangyi, thanks for showing interest in MethylSeekR. The training of the model to identify PMDs is only done on one chromosome (and one chromosome is sufficient for that in our experience), but predictions of PMDs are done for the entire genome. Are you asking whether the training could be done on all chromosomes?
best
Lukas

**Comment by Xiangyi-Deng** [comment]
> Hi Xiangyi, thanks for showing interest in MethylSeekR. The training of the model to identify PMDs is only done on one chromosome (and one chromosome is sufficient for that in our experience), but predictions of PMDs are done for the entire genome. Are you asking whether the training could be done on all chromosomes? best Lukas

Sorry, I don't get you.

Is there difference between "to identify PMDs is only done on one chromosome" and "predictions of PMDs are done for the entire genome" ?

I did it according to your package tutorial. I think I want the training could be done on all chromosomes.

By the way,  I want to look four type of segments (HMD,PMD,LMR,UMR) in one sample data. 

So  can I link this  with predictions of PMDs for the entire genome ? 

I am  confused. 

Thank you for your response.

Best,
xiangyi

**Comment by LukasBurger** [comment]
Hi Xiangyi
"to identify PMDs is only done on one chromosome" should mean: one chromosome is used to train the Hidden Markov Model. This Hidden Markov Model is then used to predict PMDs in the entire genome (this is what "predictions of PMDs are done for the entire genome" refers to). So the PMDsegments.gr object that you get after running the segmentPMDs function contains already PMDs for all chromosomes. So there is no need to change anything. Training the Hidden Markov Model on all chromosomes is not necessary in my experience and there is also currently no implementation for that. As a side note: HMDs cannot be determined using MethylSeekR.
best
Lukas

**Comment by Xiangyi-Deng** [comment]
Hi @LukasBurger ,
Thank you very much. I understand what you mean. 

It's cool.

"to identify PMDs is only done on one chromosome" should mean: one chromosome is used to train the Hidden Markov Model.    So here, which specific chromosome should be selected firstly ?

Thanks again.

Best,
xiangyi.

**Comment by Xiangyi-Deng** [comment]
Hi @LukasBurger,

I have another small question. 

Based on your tutorial, I can do the whole PMD analysis and get visualization in the end.

But when I use the below function:

`plotFinalSegmentation(m=data.gr, segs=UMRLMRsegments.gr,PMDs=PMDsegments.gr,numRegions = 4,pdfFilename="final.segmentation.example.regions.pdf",meth.cutoff=m.sel)`

I want to know the maximum  number I can set here through numRegions = n ?


If it can show segments information of all the chromosomes ?


Could you give me some advice on this question ?

Best,
xiangyi

**Comment by LukasBurger** [comment]
Hi Xiangy, regarding your first question: you can use a small autosome, for example chr22 in human as in the example code in the vignette. Regarding your second question, there is no limit to n, but the pdf may get very large... The regions are chosen randomly from the entire genome, there is no implementation to select particular regions/chromosomes if that's what you're interested in (if you know some R, you should be able to change the MethylSeekR code to retrieve specific regions from the genome though)
best
Lukas

**Comment by Xiangyi-Deng** [comment]
Thanks @LukasBurger , got it. 

Have a nice day !
