### ISSUE TITLE
How can I  compare segments produced by MethylSeekR across multiple samples 

### ISSUE THREAD

**Issue by Xiangyi-Deng** [LukasBurger/MethylSeekR#6]
Hi @LukasBurger ,

I have another question.

Now I can produce segments information of one sample each time.

But if I want to see the difference or similarity of segments distribution across several samples, should I compare the  PMD, LMR, UMR segments visualization results manually ? It is quite difficult.

And you know, all the segments visualization depends on below step:

```
numRegions = 4

plotFinalSegmentation(m=data.gr, segs=UMRLMRsegments.gr,PMDs=PMDsegments.gr,numRegions = 4,pdfFilename="final.segmentation.example.regions.pdf",meth.cutoff=m.sel)
```

And each visualization result from  each sample data contains part of all chromosomes.

However, when I do this on other samples,  I will get a visualization result in a different order in one PDF.

So could you give me some advice on my question.

Thank you in advance.

Best,
xiangyi

**Comment by LukasBurger** [comment]
Hi Xiangyi
I am afraid this can't be done in MethylSeekR and you will need to write your own code for this. Looking at the code in MethylSeekR within the plotFinalSegmentation function may help you get started with that. 
best
Lukas

**Comment by Xiangyi-Deng** [comment]
Thank you @LukasBurger .  Have a nice day.
